dtb-$(CONFIG_ARCH_MXC) += lec-imx95-g080uan02.dtb
dtb-$(CONFIG_ARCH_MXC) += lec-imx95-g156hat02.dtb
dtb-$(CONFIG_ARCH_MXC) += lec-imx95-lt9611.dtb
dtb-$(CONFIG_ARCH_MXC) += lec-imx95-lt96114k.dtb  lec-imx95-ov5640.dtb
dtb-$(CONFIG_ARCH_MXC) += lec-imx95-tpm.dtb  lec-imx95-ov13855.dtb
